services:
  - type: web
    name: russia-map-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000

  - type: web
    name: russia-map-frontend
    env: python
    buildCommand: pip install flask requests
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: https://russia-map-backend.onrender.com 